version: "3.8"

services:
  weather-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
